on:
  schedule:
    - cron: 0 15 * * 4
  repository_dispatch:
    types: [sync-workflows]

name: Sync workflows
jobs:
  release:
    name: Sync workflows
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: technote-space/auto-cancel-redundant-job@v1
        with:
          EXCLUDE_MERGED: 'true'
      - name: Sync workflows
        uses: technote-space/create-pr-action@v2
        with:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          EXECUTE_COMMANDS: |
            rm -rdf .github/workflows/.tmp
            mkdir -p .github/workflows/.tmp
            git clone --depth=1 https://github.com/technote-space/github-actions-workflows.git .github/workflows/.tmp/workflows

            bash .github/workflows/.tmp/workflows/ts-repo/copy.sh release
#            bash .github/workflows/.tmp/workflows/common/copy.sh
#            bash .github/workflows/.tmp/workflows/gh-actions/copy.sh
#            bash .github/workflows/.tmp/workflows/js-repo/copy.sh [release, release-pages, release-pages-releases, release-releases]
#            bash .github/workflows/.tmp/workflows/ts-repo/copy.sh [release, release-pages, release-pages-releases, release-releases]
#            bash .github/workflows/.tmp/workflows/wp-plugin/copy.sh
#            bash .github/workflows/.tmp/workflows/composer/copy.sh [test, test.php56]
#            bash .github/workflows/.tmp/workflows/laravel/copy.sh

#            sed -i 's/cron:.\+$/cron: 0 17 * * */' .github/workflows/update-dependencies.yml
#            sed -i 's/cron:.\+$/cron: 0 9 * * 1/' .github/workflows/update-dependencies.yml

#            sed -i "s/WP_VERSION: \[.\+$/WP_VERSION: ['latest', '5.0', 'trunk']/" .github/workflows/ci.yml

#            sed -i "s/target: \['npm', 'gpr'\]/target: ['npm']/" .github/workflows/release.yml
#            sed -i "/GH_PAGES_PLUGIN_SCRIPT/d" .github/workflows/release.yml
#            sed -i "/GH_PAGES_TEMPLATE/d" .github/workflows/release.yml
#            sed -i "s/GH_PAGES_TITLE:.*$/GH_PAGES_TITLE: jQuery Marker Animation/" .github/workflows/release.yml

#            sed -i '1,3d' .github/workflows/toc.yml
#            sed -i '1i on: push' .github/workflows/toc.yml
#            sed -i '/TARGET_BRANCH_PREFIX/d' .github/workflows/toc.yml
#            sed -i "/ACTIVATE_POPULAR_PLUGINS: 1/a \        exclude:\n          - php: '7.3'\n            WP_VERSION: '4.6'" .github/workflows/ci.yml

            rm -rdf .github/workflows/.tmp
          COMMIT_MESSAGE: 'chore: sync workflows'
          PR_BRANCH_PREFIX: chore/
          PR_BRANCH_NAME: 'chore-sync-workflows'
          PR_TITLE: 'chore: sync workflows'
          ONLY_DEFAULT_BRANCH: true
